const stepData = {
    0: {
        slideNum: 0,
        stepNum: 0,
        buttonPosition: { x: 243, y: 145 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "원하는 상품을 선택하고 [신청하기]를 눌러 주세요.",
        title: "상품선택",
    },
    1: {
        slideNum: 0,
        stepNum: 3,
        buttonPosition: { x: 161, y: 79 },
        scrollRequired: true,
        scrollAmount: 470,
        message: "상품 안내를 확인하고 카드 발급하기를 눌러주세요.",
        title: "상품선택",
    },
    2: {
        slideNum: 0,
        stepNum: 4,
        buttonPosition: { x: 516, y: 393 },
        scrollRequired: true,
        scrollAmount: 674,
        message: "상품 안내를 확인하고 카드 발급하기를 눌러주세요.",
        title: "상품선택",
    },

    3: {
        slideNum: 1,
        stepNum: 6,
        buttonPosition: { x: 457, y: 365 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "대표자 휴대폰 본인인증을\n진행해주세요.",
        title: "인증하기",
    },

    4: {
        slideNum: 2,
        stepNum: 7,
        buttonPosition: { x: 204, y: 698 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "대표자 신분증을 확인할게요.\n정보를 입력하거나 휴대폰으로 촬영해주세요.",
        title: "신분증 확인",
    },
    5: {
        slideNum: 2,
        stepNum: 9,
        buttonPosition: { x: 261, y: 700 },
        scrollRequired: true,
        scrollAmount: 220,
        message: "대표자 신분증을 확인할게요.\n정보를 입력하거나 휴대폰으로 촬영해주세요.",
        title: "신분증 확인",
    },

    6: {
        slideNum: 3,
        stepNum: 12,
        buttonPosition: { x: 449, y: 325 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "대표자 명의의 IBK기업은행 또는 다른 은행 계좌로 인증해 주세요.",
        title: "대표자 본인확인",
    },

    7: {
        slideNum: 4,
        stepNum: 15,
        buttonPosition: { x: 187, y: 816 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "홈택스에 등록된 인증서로 정보를 가져올 수 있어요.",
        title: "국세청 정보 가져오기",
    },
    8: {
        slideNum: 4,
        stepNum: 18,
        buttonPosition: { x: 516, y: 410 },
        scrollRequired: true,
        scrollAmount: 393,
        message: "홈택스에 등록된 인증서로 정보를 가져올 수 있어요.",
        title: "국세청 정보 가져오기",
    },

    9: {
        slideNum: 5,
        stepNum: 19,
        buttonPosition: { x: 135, y: 75 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "약관과 설명서를 확인하고 상품가입 시 확인사항에 동의해 주세요.",
        title: "약관동의",
    },
    10: {
        slideNum: 5,
        stepNum: 21,
        buttonPosition: { x: 202, y: 73 },
        scrollRequired: true,
        scrollAmount: 227,
        message: "약관과 설명서를 확인하고 상품가입 시 확인사항에 동의해 주세요.",
        title: "약관동의",
    },
    11: {
        slideNum: 5,
        stepNum: 26,
        buttonPosition: { x: 516, y: 363 },
        scrollRequired: true,
        scrollAmount: 300,
        message: "약관과 설명서를 확인하고 상품가입 시 확인사항에 동의해 주세요.",
        title: "약관동의",
    },

    12: {
        slideNum: 6,
        stepNum: 28,
        buttonPosition: { x: 320, y: 71 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "금융소비자 유형을 판단하기 위해 사업자 정보를 입력해 주세요.",
        title: "계약서류 제공 및 설명의무 안내",
    },
    13: {
        slideNum: 6,
        stepNum: 130,
        buttonPosition: { x: 481, y: 362 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "금융소비자 유형을 판단하기 위해 사업자 정보를 입력해 주세요.",
        title: "계약서류 제공 및 설명의무 안내",
    },
    14: {
        slideNum: 6,
        stepNum: 130,
        buttonPosition: { x: 391, y: 374 },
        scrollRequired: true,
        scrollAmount: 535,
        message: "금융소비자 유형을 판단하기 위해 사업자 정보를 입력해 주세요.",
        title: "계약서류 제공 및 설명의무 안내",
    },

    
    15: {
        slideNum: 7,
        stepNum: 13,
        buttonPosition: { x: 146, y: 74 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "대표자의 정보 수집/조회에 동의해 주세요.",
        title: "약관동의(대표자)",
    },
    16: {
        slideNum: 7,
        stepNum: 13,
        buttonPosition: { x: 316, y: 361 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "대표자의 정보 수집/조회에 동의해 주세요.",
        title: "약관동의(대표자)",
    },
    17: {
        slideNum: 7,
        stepNum: 13,
        buttonPosition: { x: 513, y: 365 },
        scrollRequired: true,
        scrollAmount: 1236,
        message: "대표자의 정보 수집/조회에 동의해 주세요.",
        title: "약관동의(대표자)",
    },

    18: {
        slideNum: 8,
        stepNum: 13,
        buttonPosition: { x: 472, y: 359 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "심사가 끝났어요. 카드발급을 계속 진행해 주세요.",
        title: "심사결과",
    },

    19: {
        slideNum: 9,
        stepNum: 13,
        buttonPosition: { x: 134, y: 73 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "발급정보를 입력해 주세요.",
        title: "발급정보 입력",
    },
    20: {
        slideNum: 9,
        stepNum: 13,
        buttonPosition: { x: 523, y: 367 },
        scrollRequired: true,
        scrollAmount: 232,
        message: "발급정보를 입력해 주세요.",
        title: "발급정보 입력",
    },

    21: {
        slideNum: 10,
        stepNum: 13,
        buttonPosition: { x: 289, y: 82 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "카드 브랜드를 선택해 주세요.",
        title: "부가정보",
    },
    22: {
        slideNum: 10,
        stepNum: 13,
        buttonPosition: { x: 201, y: 84 },
        scrollRequired: true,
        scrollAmount: 200,
        message: "카드비밀번호를 설정해주세요.",
        title: "부가정보",
    },
    23: {
        slideNum: 10,
        stepNum: 13,
        buttonPosition: { x: 256, y: 84 },
        scrollRequired: true,
        scrollAmount: 200,
        message: "공용카드 발급 매수를 선택해 주세요.(최대 10매까지)",
        title: "부가정보",
    },
    24: {
        slideNum: 10,
        stepNum: 13,
        buttonPosition: { x: 286, y: 72 },
        scrollRequired: true,
        scrollAmount: 233,
        message: "카드별 한도를 설정해주세요.",
        title: "부가정보",
    },
    25: {
        slideNum: 10,
        stepNum: 13,
        buttonPosition: { x: 520, y: 369 },
        scrollRequired: true,
        scrollAmount: 243,
        message: "정보를 모두 입력하고 확인을 눌러주세요.",
        title: "부가정보",
    },

    26: {
        slideNum: 11,
        stepNum: 13,
        buttonPosition: { x: 146, y: 72 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "고객정보를 확인 후 OTP 발생번호를 입력해 주세요.",
        title: "정보확인 및 OTP입력",
    },
    27: {
        slideNum: 11,
        stepNum: 13,
        buttonPosition: { x: 522, y: 370 },
        scrollRequired: true,
        scrollAmount: 80,
        message: "고객정보를 확인 후 OTP 발생번호를 입력해 주세요.",
        title: "정보확인 및 OTP입력",
    },

    28: {
        slideNum: 12,
        stepNum: 13,
        buttonPosition: { x: 353, y: 71 },
        scrollRequired: false,
        scrollAmount: 0,
        message: "카드발급이 완료되었습니다. 이제 카드를 등록해 보세요.",
        title: "발급완료",
    },
};

const stepDataTitle = {
    title:
        [
            '상품선택', '인증하기', '신분증확인', '대표자 본인확인',
            '국세청 정보 가져오기','약관동의','계약서류 제공 및 설명의무 안내', '약관동의(대표자)', 
            '심사결과','발급정보 입력', '부가정보', '정보확인 및 OTP입력', '발급완료'
        ]
}

const modalData = {
    title: "기업카드 발급하기",
    contentText: {
        start: "비대면으로 법인카드를\n 발급해 보세요.",
        end: "체험하기를 완료했어요.\n다른 업무도 체험해 보세요.",
    },
};
